<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNeWh1Tt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNeWh1Tt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNeWh1Tt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNeWh1Tt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNeWh1Tt\App_KernelDevDebugContainer([
    'container.build_hash' => 'NeWh1Tt',
    'container.build_id' => 'ca376047',
    'container.build_time' => 1613316460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNeWh1Tt');
